### ISSUE TITLE
self.geoFire.removeKey is not working which is very annoying

### ISSUE THREAD

**Issue by YasirAmeen** [firebase/geofire-objc#118]
I am facing the very irritating issue, self.geoFire.removeKey is not working.

some guy mentioned workaround to overcome this issue which is following,

`  let collectionRef = Database.database().reference()
                .child("groupId")
                .child("locationId")

            collectionRef.removeValue { error, ref in
                
                if error != nil {
                    reject(error!)
                    return
                }
                
                fulfill(poi)
                
            }`

the above code is deleting a key but on Android side is crashing with the following log.

`Fatal Exception: java.lang.AssertionError: Got Datasnapshot without location with key 45
       at com.firebase.geofire.GeoQuery.childChanged(GeoQuery.java:294)
       at com.firebase.geofire.GeoQuery.access$100(GeoQuery.java:51)
       at com.firebase.geofire.GeoQuery$1.onChildChanged(GeoQuery.java:79)
       at com.google.android.gms.internal.firebase_database.zzbt.zza(Unknown Source)
       at com.google.android.gms.internal.firebase_database.zzgx.zzdr(Unknown Source)
       at com.google.android.gms.internal.firebase_database.zzhd.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5910)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)`

I am not able to resolve this, my application is on production and i am going to die :-( please help

**Comment by morganchen12** [comment]
You can fix the crashing by manually re-adding the key via Firebase Console. I'll take a look at the remove key function.

**Comment by morganchen12** [comment]
Fixed in 2577952.
